In [38]:
import numpy as np
import math
import random

def isGoal(x):
    for i in range(x.shape[0]-1):
        for j in range(i+1,x.shape[0]):
            if x[i]==x[j]:
                #print("Column Conflict "+str(i)+" "+str(j))
                return False
               
            if abs(i-j) == abs(x[i]-x[j]):
                #print("Diagonal Conflict "+str(i)+" "+str(j))
                return False
              
    return True


isGoal(np.asarray([1,3,0,2]))

True

In [2]:
def generateRandomly(n):
    x=np.zeros(n)
    for i in range(x.shape[0]):
        x[i]=random.randint(0,n-1)
    return x
s=generateRandomly(4)
print(s)

[2. 2. 0. 1.]


In [6]:

def MonteCarlo(n,maxIter):
    
    for i in range(maxIter):
        s=generateRandomly(n)
        if isGoal(s):
            return s
    return "Failure"
    
MonteCarlo(4,1500)

array([2., 0., 3., 1.])

In [7]:
import copy
def generateRandomNeighbor(s):
    sprime=copy.deepcopy(s)
    # make some random changes in s
    sprime[random.randint(0,s.shape[0]-1)]=random.randint(0,s.shape[0]-1)
    return sprime

generateRandomNeighbor(np.array([0,1,2,3]))

array([0, 1, 0, 3])

In [9]:
def RandomNeighborSearch(n,maxIter):
    s = generateRandomly(n)
    if isGoal(s):
        return s
    for i in range(maxIter):
        sprime = generateRandomNeighbor(s)
        if isGoal(sprime):
            return sprime
            s=sprime
    return "Failure"

RandomNeighborSearch(4,1500)

'Failure'

In [39]:
def quality(x):
    count=0
    for i in range(x.shape[0]-1):
        for j in range(i+1,x.shape[0]):
            if x[i]==x[j]:
                #print("Column Conflict "+str(i)+" "+str(j))
                #return False
                count=count+1
            if abs(i-j) == abs(x[i]-x[j]):
                #print("Diagonal Conflict "+str(i)+" "+str(j))
                #return False
                count=count+1
    return count

In [43]:
def HillDescent(n,maxIter):
    s = generateRandomly(n)
    if isGoal(s):
        return s
    for i in range(maxIter):
        sprime = generateRandomNeighbor(s)
        if isGoal(sprime):
            return sprime
        if quality(sprime)<=quality(s):
            s=sprime
    return "Failure"

HillDescent(20,100000)

array([10., 12.,  7.,  1., 11.,  2.,  5., 19.,  8., 18., 14.,  3., 13.,
       16.,  9., 17.,  6.,  4.,  0., 15.])